# used to create the object
name: BallBalance

physics_engine: physx

# if given, will override the device setting in gym.
env:
  numEnvs: 4096
  numObservations: 24
  numActions: 3
  envSpacing: 2.0
  maxEpisodeLength: 500
  actionSpeedScale: 20
  enableDebugVis: False

  clipObservations: 5.0
  clipActions: 1.0

  # set to True if you use camera sensors in the environment
  enableCameraSensors: False

sim:
  dt: 0.01
  substeps: 1
  up_axis: 'z'
  use_gpu_pipeline: True
  gravity: [0.0, 0.0, -9.81]
  physx:
    num_threads: 4
    solver_type: 1
    use_gpu: True # set to False to run on CPU
    num_position_iterations: 8
    num_velocity_iterations: 0
    contact_offset: 0.02
    rest_offset: 0.001
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    default_buffer_size_multiplier: 5.0
    max_gpu_contact_pairs: 8388608 # 8*1024*1024
    num_subscenes: 0
    contact_collection: 0 # 0: CC_NEVER (don't collect contact info), 1: CC_LAST_SUBSTEP (collect only contacts on last substep), 2: CC_ALL_SUBSTEPS (default - all contacts)
task:
  randomize: False
