# used to create the object
name: FrankaCabinet

physics_engine: physx

# if given, will override the device setting in gym.
env:
  numEnvs: 4096
  numObservations: 23
  numActions: 9
  envSpacing: 1.5
  episodeLength: 500
  enableDebugVis: False

  clipObservations: 5.0
  clipActions: 1.0

  startPositionNoise: 0.0
  startRotationNoise: 0.0

  numProps: 16
  aggregateMode: 3

  actionScale: 7.5
  dofVelocityScale: 0.1
  distRewardScale: 2.0
  rotRewardScale: 0.5
  aroundHandleRewardScale: 0.25
  openRewardScale: 7.5
  fingerDistRewardScale: 5.0
  actionPenaltyScale: 0.01

  asset:
    assetRoot: '../assets'
    assetFileNameFranka: 'urdf/franka_description/robots/franka_panda.urdf'
    assetFileNameCabinet: 'urdf/sektion_cabinet_model/urdf/sektion_cabinet_2.urdf'

  # set to True if you use camera sensors in the environment
  enableCameraSensors: False

sim:
  dt: 0.0166 # 1/60
  substeps: 1
  up_axis: 'z'
  use_gpu_pipeline: True
  gravity: [0.0, 0.0, -9.81]
  physx:
    num_threads: 4
    solver_type: 1
    use_gpu: True # set to False to run on CPU
    num_position_iterations: 12
    num_velocity_iterations: 1
    contact_offset: 0.005
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    default_buffer_size_multiplier: 5.0
    max_gpu_contact_pairs: 1048576 # 1024*1024
    num_subscenes: 0
    contact_collection: 0 # 0: CC_NEVER (don't collect contact info), 1: CC_LAST_SUBSTEP (collect only contacts on last substep), 2: CC_ALL_SUBSTEPS (default - all contacts)

task:
  randomize: False
